name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --exclude-mail -- './**/*.html' './**/*.md'
        continue-on-error: true

      - name: Validate HTML
        run: npx html-validate --ext .html .
        continue-on-error: true
